name: finay
description: "Finasana Y project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+32

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.2.5
  cupertino_icons: ^1.0.8
  flutter_inappwebview: ^6.1.5
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  permission_handler: ^11.4.0
  local_auth: ^2.2.0
  provider: ^6.1.2
  connectivity_plus: ^6.0.1
  flutter_sound: ^9.2.13
  path_provider: ^2.1.2
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/fina2.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/FinaAndroid.png
    - assets/menu_data.json
    - assets/bottom_nav_data.json



